export const teamMembersDetails = [
  {
    id: 1,
    name: 'Sudarshan Raj Pandey',
    position: 'Founding Partner',
    email: 'srpandey@srp.com.np',
    phone: '+977-1-4720983',
    expertise: [
      'Local and International Taxation',
      'Mergers and acquisitions',
      'Advisory Services',
      'Audit and Assurance',
    ],
    industry_expertise: [
      'Banking and Financial Institutions',
      'Hydropower Companies',
      'Governmental Organizations',
      'Foreign Branches/JVs',
      'Trading Institutions',
      'Tourism Industries',
    ],
    bio: `Sudarshan Raj Pandey, founding partner of S.R. Pandey & Co., Chartered Accountants, having over 31 years of experience in the field, is the backbone of the firm. Mr. Pandey is a highly accomplished taxation expert with profound knowledge of tax laws, compliance, and strategic tax planning demonstrated through his leadership in tax policy formulation and preparation and revision of the Income Tax Manual. He has played a key role in refining Nepal’s tax laws and regulatory framework. With extensive expertise in taxation, international taxation, transfer pricing, and regulatory compliance, Mr. Pandey has successfully delivered tailored solutions for complex financial structures, helping businesses across various industries achieve tax efficiency while ensuring full compliance with legal frameworks.

He has played a key role in policy preparation for financial institutions, including operational manuals, loan write-off policies, investment guidelines, and internal audit frameworks. Additionally, he is a recognized speaker in accounting, taxation, banking, and financial management training programs.`,
    img: '/team-imgs/sudarshan-raj-pandey.png',
    content: true,
  },
  {
    id: 2,
    name: 'Bhaskar Singh Lala',
    position: 'Partner, Development Sector & Quality Assurance',
    email: 'bslala@srp.com.np',
    phone: '+977-1-4720983',
    expertise: [
      'Audit & Quality Review',
      'Public Financial Management',
      'Local Fund Agent',
    ],
    industry_expertise: [
      'Non-Governmental Organization (NGOs)',
      'International NGOs',
      'International Development Agencies',
      'Trading Institutions',
      'Banking and Financial Institutions',
    ],
    bio: `Bhaskar Singh Lala, partner at S.R. Pandey & Co., Chartered Accountants, brings 29 years of extensive experience in serving large and medium-sized clients across various industries. His core expertise includes Statutory Audits, Internal Audits, Internal Financial Controls and Business Consultancy. He has worked with diverse clients, including Banking and Financial Institutions, Non-Governmental Organizations (NGOs), and International NGOs (INGOs), providing strategic financial guidance and audit services. He has held several key leadership roles in financial management and consultancy. His expertise includes serving as a consultant in large-scale financial and social development projects, overseeing internal audit functions, and strengthening governance frameworks.`,
    img: '/team-imgs/bhaskar.png',
    content: true,
  },
  {
    id: 3,
    name: 'Rajesh Poudel',
    position: 'Partner, Insurance & Quality Assurance',
    email: 'rpoudel@srp.com.np',
    phone: '+977-1-4720983',
    expertise: ['Risk Based Audit & Quality Review'],
    industry_expertise: [
      'Insurance Companies',
      'Non-Governmental Organizations (NGOs)',
      'International NGOs',
      'International Development Agencies',
      'Bank and Financial Institutions',
      'Hydropower Companies',
    ],
    bio: `Rajesh Poudel is a partner at S.R. Pandey & Co., Chartered Accountants, bringing 29 years of extensive experience in statutory audits, risk-based internal audits, taxation advisory, business consultancy, due diligence, and NFRS implementation. He has worked with a diverse range of clients across various industries, including banking and financial institutions, non-governmental organizations (NGOs), INGOs, international development agencies, and insurance companies. His expertise has been instrumental in the successful implementation of Nepal Financial Reporting Standards (NFRS) in several banks, financial institutions, and large corporates in Nepal. Beyond audits, he is actively involved in taxation advisory, business consultancy, and internal audits using a risk-based approach, providing strategic financial guidance to various organizations.`,
    img: '/team-imgs/rajesh-poudel.png',
    content: true,
  },
  {
    id: 4,
    name: 'Arun Raut',
    position: 'Partner, Deals & Advisory',
    email: 'arunraut@srp.com.np',
    phone: '+977-1-4720983',
    expertise: [
      'Due Diligence and Valuations',
      'Deal Structuring',
      'NFRS/ IFRS Implementation',
      'Taxation and advisory services',
    ],
    industry_expertise: [
      'Banking and Financial Institutions',
      'Multinational Companies (MNCs)',
      'Governmental Organizations',
      'Fintech & IT',
      'Startups',
      'Manufacturing',
      'Service Sector',
    ],
    bio: `Arun Raut, a partner at S.R. Pandey & Co., Chartered Accountants, possesses 15 years of experience in statutory audits, risk-based internal audits, internal financial controls, taxation advisory, business consultancy, due diligence, and NFRS implementation. His expertise includes deal structuring, due diligence and NFRS implementation for various organizations. He has been actively involved in implementing Nepal Financial Reporting Standards (NFRS), guiding organizations through the transition, ensuring compliance, and enhancing financial transparency. As an engagement leader, he has overseen multiple merger and acquisition projects, focusing on due diligence reviews to assess financial health, regulatory compliance, asset quality, and potential risks. Additionally, he has contributed to structured training modules and served as a speaker in national and international forums on taxation and financial reporting standards. His expertise has been instrumental in improving financial reporting, risk management, and strategic decision-making across various sectors.`,
    img: '/team-imgs/arun.png',
    content: true,
  },
  {
    id: 5,
    name: 'Laxmi Prasad Luintel',
    position: 'Partner, Tax & Advisory',
    email: 'lpluintel@srp.com.np',
    phone: '+977-1-4720983',
    expertise: ['Risk based Audit', 'International Taxation', 'Advisory'],
    industry_expertise: [
      'Banking and Financial Institutions',
      'Non-Governmental Organizations (NGOs)',
      'International NGOs (INGOs)',
      'International Development Agencies',
      'Aviation, Healthcare',
      'Hydropower Companies',
    ],
    bio: `Possessing over a decade of extensive experience in the financial sector, Laxmi Prasad Luintel, a partner at S.R. Pandey & Co., Chartered Accountants, has developed a strong specialization in risk-based internal audits and possesses a comprehensive understanding of banking and financial institutions. He has served as a Tax consultant for a number of clients, including representation on cases relating to income tax and VAT for Administrative Review. Additionally, as a quality control reviewer, he ensures compliance and best practices in audits and financial projects across multiple sectors.`,
    img: '/team-imgs/laxmi.png',
    content: true,
  },
  {
    id: 6,
    name: 'Sandesh Ratna Shakya',
    position: 'Partner, Audit & Assurance',
    email: 'sandeshshakya@srp.com.np',
    phone: '+977-1-4720983',
    expertise: ['Risk Based Audit', 'CFO Advisory'],
    industry_expertise: [
      'Trading',
      'Manufacturing',
      'Service-related Companies',
      'Non-Governmental Organization (NGOs)',
      'International NGOs (INGOs)',
    ],
    bio: `Sandesh Ratna Shakya, a partner at S.R. Pandey & Co., is associated with the firm for more than 10 years. He specializes in audit & assurance and tax advisory services, with a strong focus on private sector enterprises. As an engagement leader, he plays a key role in financial reviews and compliance assessments helping businesses navigate complex legal and regulatory requirements. His expertise extends to providing strategic financial insights that support business growth and sustainability. He has been involved in tax compliance review of national / multinational companies, NGO / INGO and preparation of training material regarding tax laws in Nepal.`,
    img: '/team-imgs/sandesh-ratna.png',
    content: true,
  },
  {
    name: 'Rasmila Maharjan',
    position: 'Manager',
    img: '/team-imgs/rasmila.png',
    id: 7,
    email: 'rasmila.maharjan@srp.com.np',
    phone: '+977-1-4720983',
    content: false,
  },
  {
    name: 'Astha Bista',
    position: 'Manager',
    img: '/team-imgs/astha.png',
    id: 8,
    email: 'astha.bista@srp.com.np',
    phone: '+977-1-4720983',
    content: false,
  },
  {
    name: 'Santosh Sah',
    position: 'Manager',
    img: '/team-imgs/santosh-shah.png',
    id: 9,
    email: 'santosh.sah@srp.com.np',
    phone: '+977-1-4720983 ',
    content: false,
  },
];
